import { useMemo, useState, type FormEvent } from 'react';
import { buildPlan, paceGuide, scheduleChangePolicy, stations, season, planReviewed, type MarathonChoice } from './trainingPlan';
import { races, procamEvents } from './raceData';
import { roadResults } from './performanceData';
import { resultDetails } from './resultDetails';
import { raceHistory, singlesStationTrend } from './hyroxHistory';
import oldGarmin from './data/garmin-weekly.json';
import type { Day } from './trainingHistory';
import './styles.css';

type Entry = Record<string, string | number>;
type Snapshot = {lastSuccessfulSnapshotAt?: string; healthByDate?: Record<string, Record<string,number>>; activities?: Record<string, unknown>[]; fitnessProfile?: Record<string,unknown>; supplementPurchases?: {product:string;purchased:string;use:string}[]; bodyComposition?: unknown[]};
const keys=['rmr_completed_v4','ap_training_checkins_v1','ap_training_sessions_v1','ap_private_garmin_v1','ap_marathon_branch_v1'];
function read<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function dateOf(d:Day){if(d.iso)return d.iso;const [day,mon]=d.date.split(' ');const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];return `2026-${String(months.indexOf(mon)+1).padStart(2,'0')}-${day.padStart(2,'0')}`;}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Table({heads,rows}:{heads:string[];rows:(string|number)[][]}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
export default function App(){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());
 const [tab,setTab]=useState(location.hash==='#results'?'records':location.hash==='#season'?'season':'plan');
 const [choice,setChoice]=useState<MarathonChoice>(()=>{const v=read<string>('ap_marathon_branch_v1','none');return v==='osaka'||v==='tokyo'?v:'none';});
 const weeks=useMemo(()=>buildPlan(choice),[choice]);
 const current=weeks.find(w=>w.days.some(d=>dateOf(d)===today))||weeks[weeks.length-1];
 const [weekId,setWeekId]=useState(current.id);
 const week=weeks.find(w=>w.id===weekId)||current;
 const [completed,setCompleted]=useState<Record<string,boolean>>(()=>read('rmr_completed_v4',{}));
 const [checkins,setCheckins]=useState<Entry[]>(()=>read('ap_training_checkins_v1',[]));
 const [logs,setLogs]=useState<Entry[]>(()=>read('ap_training_sessions_v1',[]));
 const [snapshot,setSnapshot]=useState<Snapshot>(()=>read('ap_private_garmin_v1',{}));
 const [message,setMessage]=useState('');
 const [archive,setArchive]=useState(false);
 const [recordView,setRecordView]=useState(location.hash==='#results'?'results':'daily');
 const latest=checkins.filter(x=>x.checkin_date===today).at(-1);
 const readiness=!latest?'Check-in needed':Number(latest.pain_score)>=3?'Stop impact / reassess':Number(latest.pain_score)>=1||Number(latest.sleep_hours)<6?'Modify · no double':'Proceed if warm-up feels normal';
 function save(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));setMessage('Saved on this device');return true;}catch{setMessage('Could not save: device storage is unavailable or full. Export a backup.');return false;}}
 function toggle(id:string){const next={...completed,[id]:!completed[id]};if(save(keys[0],next))setCompleted(next);}
 function checkin(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const entry:Entry={checkin_date:String(f.get('date')),sleep_hours:String(f.get('sleep')),pain_score:String(f.get('pain')),body_battery:String(f.get('battery')||''),session_rpe:String(f.get('rpe')||''),note:String(f.get('note')||''),weight_kg:String(f.get('weight')||''),waist_cm:String(f.get('waist')||''),hrv_ms:String(f.get('hrv')||''),resting_hr:String(f.get('rhr')||'')};const next=[...checkins.filter(x=>x.checkin_date!==entry.checkin_date),entry].sort((a,b)=>String(a.checkin_date).localeCompare(String(b.checkin_date)));if(save(keys[1],next))setCheckins(next);}
 function session(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const entry=Object.fromEntries(f.entries()) as Entry;entry.id=crypto.randomUUID();entry.load=Number(entry.minutes)*Number(entry.rpe);const next=[...logs,entry];if(save(keys[2],next)){setLogs(next);e.currentTarget.reset();}}
 async function importData(file?:File){if(!file)return;try{const data=JSON.parse(await file.text());if(typeof data.lastSuccessfulSnapshotAt==='string'&&data.healthByDate&&typeof data.healthByDate==='object'&&!Array.isArray(data.healthByDate)){if(data.activities&&!Array.isArray(data.activities))throw new Error('Activities');for(const [date,h] of Object.entries(data.healthByDate)){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!h||typeof h!=='object')throw new Error('Health');}const byId=new Map([...(snapshot.activities||[]),...(data.activities||[])].map(x=>[x.id,x]));const next={...snapshot,...data,healthByDate:{...snapshot.healthByDate,...data.healthByDate},activities:[...byId.values()]};if(save(keys[3],next))setSnapshot(next);}else if(data.version===1&&data.storage){
 if(!data.storage||typeof data.storage!=='object')throw new Error('Backup');const values:Record<string,unknown>={};for(const key of keys){if(data.storage[key]!==undefined)values[key]=data.storage[key];}
 if(values[keys[0]]&&(typeof values[keys[0]]!=='object'||Array.isArray(values[keys[0]])))throw new Error('Completions');for(const k of [keys[1],keys[2]])if(values[k]!==undefined&&!Array.isArray(values[k]))throw new Error('Records');if(values[keys[4]]!==undefined&&!['none','osaka','tokyo'].includes(String(values[keys[4]])))throw new Error('Branch');if(values[keys[0]])values[keys[0]]={...completed,...values[keys[0]] as object};
 for(const key of [keys[1],keys[2]])if(Array.isArray(values[key])){const old=key===keys[1]?checkins:logs;const map=new Map([...old,...values[key] as Entry[]].map(x=>[String(x.id||x.checkin_date||JSON.stringify(x)),x]));values[key]=[...map.values()];}
 if(values[keys[3]]){const imported=values[keys[3]] as Snapshot;if(typeof imported!=='object'||(imported.activities&&!Array.isArray(imported.activities)))throw new Error('Snapshot');values[keys[3]]={...snapshot,...imported,healthByDate:{...snapshot.healthByDate,...imported.healthByDate},activities:[...new Map([...(snapshot.activities||[]),...(imported.activities||[])].map(x=>[x.id,x])).values()]};}const previous=Object.fromEntries(Object.keys(values).map(k=>[k,localStorage.getItem(k)]));try{for(const [key,value]of Object.entries(values))localStorage.setItem(key,JSON.stringify(value));}catch(error){for(const [key,value]of Object.entries(previous)){if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value);}throw error;}location.reload();
 }else throw new Error('Shape');}catch{setMessage('Import failed. Use a Race HQ backup or compact Garmin snapshot JSON. Existing records are retained.');}}
 const actualRows=weeks.flatMap(w=>w.days).filter(d=>dateOf(d)<='2026-09-20'&&(/completed|verified/i.test(d.title)||d.note?.includes('verified')));
 return <main className="app-shell">
 <header className="hero"><div><p className="eyebrow">AMAR PANDEY / ENDURANCE LAB</p><h1>Earn the<br/><span>next level.</span></h1><p>Run faster. Move stronger. Recover well enough to repeat.</p></div><div className="hero-meta"><span className="tag">SEASON 2026 / 27</span><h2>09 JAN</h2><p>Hong Kong · Pro Doubles peak</p><small>Plan reviewed {planReviewed} · daily calendar through 13 Jun 2027</small></div></header>
 <nav aria-label="Main navigation">{[['plan','Training'],['records','Records & Garmin'],['coach','Coaching'],['races','Race HQ'],['season','Season']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {message&&<p className="save-message" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss message">×</button></p>}
 {tab==='plan'&&<section><div className="section-head"><div><p className="eyebrow">01 / THE WORK</p><h2>Your daily prescription</h2><p>Primary training first. Open a day for exercises, pace, load, rest and an optional second session.</p></div><button onClick={()=>{setWeekId(current.id);setArchive(false)}}>Today’s week</button></div>
 <div className="controls"><label>Training week<select value={week.id} onChange={e=>setWeekId(e.target.value)}>{weeks.filter(w=>archive||dateOf(w.days[6])>=today||w.id===weekId).map(w=><option key={w.id} value={w.id}>{w.label} · {w.dates} · {w.phase}</option>)}</select></label><label className="inline"><input type="checkbox" checked={archive} onChange={e=>setArchive(e.target.checked)}/>Include historical weeks</label></div>
 <div className="week-heading"><div><span className="tag">{week.phase}</span><h3>{week.dates}</h3><p>{week.focus}</p></div><strong>{week.days.filter(d=>completed[d.id]).length}<small> / 7 marked</small></strong></div>
 <div className="callout"><b>{readiness}</b><p>{week.gate||'Historical prescriptions and verified workout details are preserved. A checkbox is your own log; it does not prove a Garmin completion.'}</p></div>
 <div className="day-list">{week.days.map(d=><details className="day-card" key={d.id} open={dateOf(d)===today?true:undefined}><summary><span className="date">{d.dow}<b>{d.date}</b></span><span className="day-name"><b>{d.title}</b><small>{d.duration} · RPE {d.rpe}</small></span><span className="tag">{d.type}</span><span className="expand">+</span></summary><div className="day-content"><label className="inline completion"><input type="checkbox" checked={!!completed[d.id]} onChange={()=>toggle(d.id)}/>Primary completed</label>{d.blocks?.map((b,i)=><div className="workout-block" key={i}><h4>{b.label}</h4><ul>{b.items.map((item,j)=><li key={j}>{item}</li>)}</ul></div>)}{d.note&&<p className="coach-note">{d.note}</p>}{d.secondary&&<div className="secondary"><p className="eyebrow">SECOND SESSION / OPTIONAL</p><h4>{d.secondary.title}</h4><ul>{d.secondary.items.map(x=><li key={x}>{x}</li>)}</ul>{!d.secondary.title.startsWith('No second')&&<label className="inline"><input type="checkbox" checked={!!completed[d.id+'-secondary']} onChange={()=>toggle(d.id+'-secondary')}/>Optional session completed</label>}</div>}</div></details>)}</div>
 <p className="muted">Future weeks are detailed provisional prescriptions, not completed records or automatic escalation. Review weekly; repeat a week when recovery or consistency is inadequate. Pace recalibration and progression rules live in Coaching.</p></section>}
 {tab==='records'&&<section><div className="section-head"><div><p className="eyebrow">02 / THE EVIDENCE</p><h2>Records & Garmin</h2><p>One record centre. Device metrics, self-reports and verified results keep their source labels.</p></div><button onClick={()=>download('race-hq-private-backup.json',{version:1,exportedAt:new Date().toISOString(),storage:Object.fromEntries(keys.map(k=>[k,read(k,null)]))})}>Export private backup</button></div>
 <div className="metric-grid"><article><small>LAST ARCHIVE</small><b>20 SEP</b><p>2026 · 17:25 HKT. Archive timestamp; no live sync.</p></article><article><small>LATEST VERIFIED RUN</small><b>15.16 km</b><p>20 Sep · 1:30:01 · approximately 5:56/km.</p></article><article><small>WORKOUT AUTHORITY</small><b>Original plan retained</b><p>Monday lower-body work stays conditional on normal walking, stairs, warm-up mechanics and symptoms.</p></article><article><small>PRIVATE DATA</small><b>{Object.keys(snapshot.healthByDate||{}).length} days</b><p>Imported health history on this device. Not sent to the public website.</p></article></div>
 <div className="callout"><b>Freshness is explicit</b><p>The compact archive is current through 20 September; the latest day may still be partial and this is not a complete weekly analysis. The old August review is retained below as historical context. There is no live Garmin connection in this public page.</p><label className="file-button">Import private snapshot / backup<input type="file" accept="application/json,.json" onChange={e=>importData(e.target.files?.[0])}/></label><p>Private entries stay in this browser, are not encrypted and do not sync automatically. Export a backup before changing device or clearing browser data. Never use a shared device for sensitive notes.</p></div>
 <div className="subnav">{[['daily','Daily health'],['sessions','Training log'],['results','Verified results']].map(([id,label])=><button key={id} className={recordView===id?'active':''} onClick={()=>setRecordView(id)}>{label}</button>)}</div>
 {recordView==='daily'&&<><h3>Daily check-in</h3><form onSubmit={checkin}><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Sleep hours<input name="sleep" type="number" min="0" max="24" step="0.1" required/></label><label>Pain 0–10<input name="pain" type="number" min="0" max="10" required/></label><label>Body Battery, if measured<input name="battery" type="number" min="0" max="100"/></label><label>Resting heart rate<input name="rhr" type="number" min="20" max="200"/></label><label>HRV, ms<input name="hrv" type="number" min="1" max="300"/></label><label>Weight, kg (optional)<input name="weight" type="number" min="25" max="250" step="0.1"/></label><label>Waist, cm (optional)<input name="waist" type="number" min="30" max="250" step="0.1"/></label><label className="wide">Symptoms, energy, supplements actually taken, clinical notes<textarea name="note" rows={3}/></label><button type="submit">Save check-in</button></form><p className="muted">Blank means not measured. Body composition is not available from the latest Garmin archive. Weight/waist trends need consistent measurement; no calorie or body-fat target has been invented.</p>
 {checkins.length>0?<Table heads={['Date','Sleep h','Pain','Weight kg','Waist cm','Notes']} rows={[...checkins].sort((a,b)=>String(b.checkin_date).localeCompare(String(a.checkin_date))).map(x=>[String(x.checkin_date),x.sleep_hours||'—',x.pain_score??'—',x.weight_kg||'—',x.waist_cm||'—',x.note||''])}/>:<p className="empty">No daily check-ins saved on this device.</p>}
 <h3>Imported Garmin health history</h3>{snapshot.lastSuccessfulSnapshotAt&&<p>Snapshot: {snapshot.lastSuccessfulSnapshotAt} · latest calendar day may be partial.</p>}{Object.keys(snapshot.healthByDate||{}).length>0?<Table heads={['Date','Sleep h','Sleep score','RHR','HRV ms','Stress','BB high / low']} rows={Object.entries(snapshot.healthByDate||{}).sort(([a],[b])=>b.localeCompare(a)).map(([date,h])=>[date,h.sleepHours??'—',h.sleepScore??'—',h.restingHeartRate??'—',h.hrvAverageMs??'—',h.stressAverage??'—',`${h.bodyBatteryHigh??'—'} / ${h.bodyBatteryLow??'—'}`])}/>:<p className="empty">Import your private compact snapshot to view sleep, HRV, stress and Body Battery here.</p>}{snapshot.supplementPurchases?.length ? <><h3>Private purchase inventory</h3><Table heads={['Product','Evidence date','Use status']} rows={snapshot.supplementPurchases.map(x=>[x.product,x.purchased,x.use])}/></> : null}</>}
 {recordView==='sessions'&&<><h3>Log actual work</h3><form onSubmit={session}><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Session<select name="slot"><option>Primary</option><option>Optional second</option><option>Unplanned</option></select></label><label>Duration, min<input name="minutes" type="number" min="1" max="600" required/></label><label>Session RPE 0–10<input name="rpe" type="number" min="0" max="10" required/></label><label className="wide">Exercise details / load / sets / pace / rest<textarea name="details" placeholder="Example: sled mass 42 kg + plates 110 kg = 152 kg total; 3 × 12.5 m; 24/25/25 sec; RPE 6" required/></label><button>Save session</button></form><p>Load = minutes × session RPE. It is a personal trend measure, not an injury prediction. Do not add Garmin and manual duration for the same session.</p>{logs.length>0&&<Table heads={['Date','Session','Minutes','RPE','Load','Details']} rows={[...logs].reverse().map(x=>[x.date,x.slot,x.minutes,x.rpe,x.load,x.details])}/>}
 <h3>Verified training archive</h3><p>Detailed historical prescriptions and corrections remain accessible through the Training week selector. Completion checkboxes are preserved separately.</p><Table heads={['Date','Session','Evidence']} rows={actualRows.map(d=>[d.date,d.title,d.note||d.duration])}/><details><summary>Imported device activities ({snapshot.activities?.length||0})</summary><Table heads={['Date','Type','Distance km','Duration min']} rows={(snapshot.activities||[]).map(a=>[String(a.date||''),String(a.type||''),String(a.distanceKm??'—'),Math.round(Number(a.durationSeconds||0)/60)])}/></details></>}
 {recordView==='results'&&<><h3>Road results</h3><Table heads={['Date','Event','Distance','Net','Official','Pace','Context']} rows={roadResults.map(r=>[r.date,r.event,r.distance,r.net,r.official,r.pace,r.result])}/><h3>HYROX results</h3><Table heads={['Event','Division','Time','Context']} rows={raceHistory}/>{resultDetails.map((rows,i)=><details key={i}><summary>{['Kerry marathon checkpoints · chip cumulative','SCHK marathon checkpoints · official cumulative','Taipei Open Singles · complete station record'][i]}</summary><Table heads={rows[0]} rows={rows.slice(1)}/>{i===2&&<p>Station total 43:08; run 44:08; arithmetic leaves 10:06 for Roxzone/non-station time. The original HQ summary reports 10:10; the four-second discrepancy is retained.</p>}</details>)}<h3>Station priorities from historical singles</h3><Table heads={['Station','Earlier','Later Pro','Development need']} rows={singlesStationTrend}/><p>Different venues, loads and partners limit comparisons. Team times and device predictions are not individual race benchmarks.</p></>}
 <details className="archive"><summary>Historical Garmin aggregate · August 2026</summary><p>This dated review is preserved, not used as today’s readiness instruction.</p><p>{oldGarmin.summary}</p><Table heads={['Historical metric','Value','Context']} rows={oldGarmin.metrics.map(m=>[m.label,m.value,m.trend])}/></details></section>}
 {tab==='coach'&&<section><p className="eyebrow">03 / EXECUTION</p><h2>Specific enough to train well</h2><div className="callout"><b>Demanding training, earned progression</b><p>The standard is consistent, repeatable work. Protect two strength sessions, one running-quality session, one controlled HYROX session, easy aerobic work and recovery. Optional training never turns every day into a hard day.</p></div>
 <h3>Workout-change safeguard</h3><Table heads={['Check','Rule']} rows={scheduleChangePolicy}/><p>For tomorrow’s threshold session, use the start-line check after the warm-up. Feeling normal keeps the original prescription in place; any abnormal symptom changes execution at that point, without rewriting the future plan.</p>
 <h3>Running pace guide</h3><p>Provisional coaching ranges from recent training and verified race context, not lab-measured zones. Start at the slower end. Heat, terrain and symptoms override the numbers; treadmill and outdoor pace are not interchangeable.</p><Table heads={['Purpose','Starting pace','Execution']} rows={paceGuide}/><p>After two controlled threshold sessions with even splits and no worse next-day symptoms, adjust by at most 5 sec/km. Every four weeks replace—not add to—the quality session with a repeatable 20-min controlled effort on the same route/treadmill and compare pace at similar effort. A clean 5K race can recalibrate later. Sub-20 5K and sub-4 marathon remain goals, not present training paces.</p>
 <h3>HYROX Pro Doubles Men · race standard</h3><Table heads={['Station','Team distance / repetitions','Race load']} rows={stations}/><p>Each athlete runs all 8 × 1 km; station work is shared. <a href="https://maintain.hyrox.com/rulebooks/HYROX_RulebookDoubles_EN.pdf" target="_blank" rel="noreferrer">Official 2026/27 doubles rulebook</a> · confirm final event briefing before racing.</p>
 <h3>Sled calibration for your gym</h3><div className="callout"><b>152 kg on one carpet is not “75% race resistance”.</b><p>Soft carpet can increase drag. More load may make the task harder still. Friction, sled runners, carpet direction and technique prevent a reliable conversion from kilograms to race effort.</p></div><ol><li>Weigh or verify the empty sled. Record total = sled + plates. Keep the lane, shoes, direction and sled fixed.</li><li>Start the programmed push at 152 kg total and pull at 103 kg total, or lower if movement stalls. Perform 3 × 12.5 m with 2 min rest. Record each time and RPE.</li><li>Target RPE 6–7, uninterrupted movement and last length within approximately 10% of the first. This is a coaching repeatability gate, not a validated race-equivalence formula.</li><li>If all three lengths are clean for two sessions and the next morning is normal, add 5–10 kg total next time. If technique deteriorates, reduce load by 10–20%. Never increase load and rounds in the same week.</li><li>Practise official 202/153 kg totals on race-like equipment when available, initially 2 × 12.5 m each with full recovery. Compare execution, not just weight. The logged 235/170 kg best efforts do not automatically become working loads.</li></ol>
 <h3>Building blocks now placed in the plan</h3><Table heads={['Capacity','Prescription / placement','Progression gate']} rows={[
 ['Single-leg strength & posterior chain','Lower day: split squat/step-up, RDL, curl','2–3 reps in reserve; symptom-free range'],['Calf / soleus / shin capacity','Lower day: both calf positions + tibialis raises','Slow controlled reps; next-day response'],['Grip & carries','Alternate HYROX force session, 50 m carries','48 kg total → 64 kg total after repeatable lengths'],['Ski / row economy','Alternate HYROX durability session','Log pace/500 m, consistent stroke rate'],['Lunges & wall balls','Alternating station days; legal reps before density','20 → 30 kg lunges; 9 kg ball only with legal form'],['Power / running mechanics','On an easy day: 4 × 15-sec relaxed strides, 75-sec walk/jog','Only after two symptom-stable weeks; replaces extra conditioning'],['Trunk & upper-body muscle','Two primary strength days + selected optional support','Progress reps, no compound failure'],['Fuel tolerance & partner execution','Long runs / HYROX rehearsals','Log carbohydrate/hour, gut response, changes and breaks']
 ]}/><h3>Optional second-session rules</h3><p>Every future day has an explicit second-session decision. Separate workouts by at least six hours. Begin with one extra aerobic session/week; cap at two after two recovered weeks. Mobility is fine more often. Skip doubles after poor sleep, persistent soreness, illness or a harder-than-planned primary. Never shorten sleep to train twice.</p>
 <h3>Fuel, supplements & physique</h3><p>Prioritise regular meals and carbohydrate around demanding sessions. Aim for roughly 1.6–2.0 g protein/kg/day from food plus supplemental protein only as needed, spread across meals. Long runs are opportunities to practise 30–60 g carbohydrate/hour. Hydration needs vary; use thirst, conditions and measured sweat loss rather than forcing litres.</p><Table heads={['Product type','Role','Use decision']} rows={[
 ['Whey isolate','Convenient complete protein','20–30 g protein when a meal is impractical; count toward daily intake, not an extra requirement'],['Glutamine','No consistent performance or muscle-building benefit in adequately nourished athletes','Low priority; no automatic daily protocol'],['Collagen peptides','Potential adjunct; evidence remains limited','Does not replace complete protein or progressive rehabilitation'],['Magnesium glycinate','Correct inadequate intake when indicated','Check elemental magnesium on label and other products; more is not better'],['Multivitamin','Possible dietary gap coverage','Avoid stacked high-dose micronutrients; no promised endurance benefit'],['Creatine monohydrate','Evidence for strength / repeated high-intensity work','Optional future discussion, not inferred as purchased or required; body-mass and tolerance trade-offs']
 ]}/><p>Purchases do not establish what you currently take. Log actual products, doses and tolerance privately in Records. Verify batch testing for competitive sport. Magnesium from supplements can cause diarrhoea and interact with some medicines; review the actual label and medicines before a dose recommendation. See <a href="https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/">NIH performance supplement guidance</a> and <a href="https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional/">NIH magnesium guidance</a>.</p><p>For visible abs, first establish consistent weight/waist measurements, food intake and training tolerance. Avoid aggressive dieting through race builds: low energy availability can harm male athletes’ health and performance. <a href="https://bjsm.bmj.com/content/57/17/1073">IOC REDs consensus</a>. No physique deadline or professional-athlete guarantee is credible from the current evidence.</p></section>}
 {tab==='races'&&<section><p className="eyebrow">04 / RACE HQ</p><h2>One race campaign</h2>{[['Confirmed & training toward',races.filter(r=>r.category==='campaign'&&r.status!=='DONE'&&!r.status.includes('CONFLICT'))],['Registration opportunities',races.filter(r=>r.category!=='campaign')],['Inactive / retained entry record',races.filter(r=>r.status.includes('CONFLICT'))]].map(([title,list])=><div key={String(title)}><h3>{String(title)}</h3><div className="race-grid">{(list as typeof races).map(r=><article key={r.name}><span className="tag">{r.status}</span><h4>{r.name}</h4><b>{r.date} · {r.type}</b><p>{r.note}</p>{r.sourceUrl&&<a href={r.sourceUrl} target="_blank" rel="noreferrer">{r.sourceLabel}</a>}<small>Reviewed {r.checked}</small></article>)}</div></div>)}<details><summary>Optional Procam sequence</summary>{procamEvents.map(r=><article key={r.name}><h4>{r.name} · {r.date}</h4><p>{r.registration} · {r.fit}</p><a href={r.sourceUrl}>Official information</a></article>)}</details><p>Completed events are in Records. A target is a committed planning goal, not proof of personal registration. Ballots remain unconfirmed until selected and paid.</p></section>}
 {tab==='season'&&<section><p className="eyebrow">05 / THE LONG VIEW</p><h2>Through June. One peak at a time.</h2><Table heads={['Window','Focus','Decision']} rows={season}/><h3>Japan marathon branch</h3><p>Both ballots are pending. The default plan is hybrid. Select a branch here only once entry is accepted and paid; this local planning choice does not change registration status in Race HQ.</p><label>Active training branch<select value={choice} onChange={e=>{const v=e.target.value as MarathonChoice;if(save(keys[4],v))setChoice(v)}}><option value="none">Hybrid · no paid Japan entry yet</option><option value="osaka">Osaka only · 28 February 2027</option><option value="tokyo">Tokyo only · 7 March 2027</option></select></label><p>Tokyo result 18 Sep; Osaka 28 Sep. If Tokyo is secured, do not also train for Osaka. Japan activation removes competing February/March HYROX work and provides post-marathon recovery.</p><h3>Weekly review</h3><ol><li>Compare planned and actual sessions, including optional work. Do not increase intensity and total duration simultaneously.</li><li>Review symptoms, sleep, energy and repeatable workout performance. Garmin HRV and Body Battery are context, never a diagnosis or permission to ignore pain.</li><li>If sessions are repeatedly missed or recovery worsens, repeat or reduce the next week. If stable, progress one variable.</li><li>Recheck race acceptance, availability and partner plans before activating a taper. Future opportunities never silently become races.</li></ol></section>}
 <footer>AMAR / ENDURANCE LAB <span>One plan · one record · consistent progression</span></footer>
 </main>;
}
