import { useMemo, useState, type FormEvent } from 'react';
import { buildPlan, paceGuide, scheduleChangePolicy, stations, season, planReviewed } from './trainingPlan';
import { seasonGoals, performanceMarkers, A_RACES, runnaLessons } from './seasonPlan';
import { chronologicalRaces as races, procamEvents } from './raceData';
import { roadResults } from './performanceData';
import { resultDetails } from './resultDetails';
import { raceHistory, singlesStationTrend } from './hyroxHistory';
import oldGarmin from './data/garmin-weekly.json';
import completions from './data/completions.json';
import strengthLog from './data/strength.json';
type Completion = {date:string;type?:string;source?:string;planned:string;title:string;distanceKm?:number;time?:string;pace?:string;avgHr?:number;maxHr?:number;reps?:string;stations?:string;note?:string};
type StrengthEntry = {date:string;session:string;exercises:{name:string;sets:{kg?:number;reps:number}[]}[];note?:string};
const topSet=(sets:{kg?:number;reps:number}[])=>{const best=[...sets].sort((a,b)=>(b.kg??0)-(a.kg??0)||b.reps-a.reps)[0];return best.kg!==undefined?`${best.kg} kg × ${best.reps}`:`${best.reps} reps`;};
import type { Day } from './trainingHistory';
import './styles.css';

type Entry = Record<string, string | number>;
type Snapshot = {lastSuccessfulSnapshotAt?: string; healthByDate?: Record<string, Record<string,number>>; activities?: Record<string, unknown>[]; fitnessProfile?: Record<string,unknown>; supplementPurchases?: {product:string;purchased:string;use:string}[]; bodyComposition?: unknown[]};
const keys=['rmr_completed_v4','ap_training_checkins_v1','ap_training_sessions_v1','ap_private_garmin_v1','ap_marathon_branch_v1'];
function read<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function dateOf(d:Day){if(d.iso)return d.iso;const [day,mon]=d.date.split(' ');const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];return `2026-${String(months.indexOf(mon)+1).padStart(2,'0')}-${day.padStart(2,'0')}`;}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Table({heads,rows}:{heads:string[];rows:(string|number)[][]}){return <div className="table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
export default function App(){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong'}).format(new Date());
 const [tab,setTab]=useState(location.hash==='#results'?'records':location.hash==='#season'?'season':'plan');
 const weeks=useMemo(()=>buildPlan(),[]);
 const nextRace=weeks.flatMap(w=>w.days).find(d=>d.race&&d.iso!>=today&&A_RACES.includes(d.iso!));
 const upcoming=weeks.filter(w=>dateOf(w.days[6])>=today).slice(0,6);
 const current=weeks.find(w=>w.days.some(d=>dateOf(d)===today))||weeks[weeks.length-1];
 const [weekId,setWeekId]=useState(current.id);
 const week=weeks.find(w=>w.id===weekId)||current;
 const [completed,setCompleted]=useState<Record<string,boolean>>(()=>read('rmr_completed_v4',{}));
 const [checkins]=useState<Entry[]>(()=>read('ap_training_checkins_v1',[]));
 const [logs,setLogs]=useState<Entry[]>(()=>read('ap_training_sessions_v1',[]));
 const [snapshot,setSnapshot]=useState<Snapshot>(()=>read('ap_private_garmin_v1',{}));
 const [message,setMessage]=useState('');
 const [archive,setArchive]=useState(false);
 const [recordView,setRecordView]=useState(location.hash==='#results'?'results':'daily');
 function save(key:string,value:unknown){try{localStorage.setItem(key,JSON.stringify(value));setMessage('Saved on this device');return true;}catch{setMessage('Could not save: device storage is unavailable or full. Export a backup.');return false;}}
 function toggle(id:string){const next={...completed,[id]:!completed[id]};if(save(keys[0],next))setCompleted(next);}
 function session(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const entry=Object.fromEntries(f.entries()) as Entry;entry.id=crypto.randomUUID();entry.load=Number(entry.minutes)*Number(entry.rpe);const next=[...logs,entry];if(save(keys[2],next)){setLogs(next);e.currentTarget.reset();}}
 async function importData(file?:File){if(!file)return;try{const data=JSON.parse(await file.text());if(typeof data.lastSuccessfulSnapshotAt==='string'&&data.healthByDate&&typeof data.healthByDate==='object'&&!Array.isArray(data.healthByDate)){if(data.activities&&!Array.isArray(data.activities))throw new Error('Activities');for(const [date,h] of Object.entries(data.healthByDate)){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!h||typeof h!=='object')throw new Error('Health');}const byId=new Map([...(snapshot.activities||[]),...(data.activities||[])].map(x=>[x.id,x]));const next={...snapshot,...data,healthByDate:{...snapshot.healthByDate,...data.healthByDate},activities:[...byId.values()]};if(save(keys[3],next))setSnapshot(next);}else if(data.version===1&&data.storage){
 if(!data.storage||typeof data.storage!=='object')throw new Error('Backup');const values:Record<string,unknown>={};for(const key of keys){if(data.storage[key]!==undefined)values[key]=data.storage[key];}
 if(values[keys[0]]&&(typeof values[keys[0]]!=='object'||Array.isArray(values[keys[0]])))throw new Error('Completions');for(const k of [keys[1],keys[2]])if(values[k]!==undefined&&!Array.isArray(values[k]))throw new Error('Records');if(values[keys[4]]!==undefined&&!['none','osaka','tokyo'].includes(String(values[keys[4]])))throw new Error('Branch');if(values[keys[4]]==='tokyo')values[keys[4]]='none';if(values[keys[0]])values[keys[0]]={...completed,...values[keys[0]] as object};
 for(const key of [keys[1],keys[2]])if(Array.isArray(values[key])){const old=key===keys[1]?checkins:logs;const map=new Map([...old,...values[key] as Entry[]].map(x=>[String(x.id||x.checkin_date||JSON.stringify(x)),x]));values[key]=[...map.values()];}
 if(values[keys[3]]){const imported=values[keys[3]] as Snapshot;if(typeof imported!=='object'||(imported.activities&&!Array.isArray(imported.activities)))throw new Error('Snapshot');values[keys[3]]={...snapshot,...imported,healthByDate:{...snapshot.healthByDate,...imported.healthByDate},activities:[...new Map([...(snapshot.activities||[]),...(imported.activities||[])].map(x=>[x.id,x])).values()]};}const previous=Object.fromEntries(Object.keys(values).map(k=>[k,localStorage.getItem(k)]));try{for(const [key,value]of Object.entries(values))localStorage.setItem(key,JSON.stringify(value));}catch(error){for(const [key,value]of Object.entries(previous)){if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value);}throw error;}location.reload();
 }else throw new Error('Shape');}catch{setMessage('Import failed. Use a Race HQ backup or compact Garmin snapshot JSON. Existing records are retained.');}}
 const actualRows=weeks.flatMap(w=>w.days).filter(d=>dateOf(d)<='2026-09-20'&&(/completed|verified/i.test(d.title)||d.note?.includes('verified')));
 return <main className="app-shell">
 <header className="hero"><div><p className="eyebrow">AMAR PANDEY / ENDURANCE LAB</p><h1>Earn the<br/><span>next level.</span></h1><p>Run faster. Move stronger. Recover well enough to repeat.</p></div><div className="hero-meta"><span className="tag">SEASON 2026 / 27</span><h2>{nextRace?.date??'—'}</h2><p>{nextRace?.title.split(' · RACE')[0]??'Season complete'}</p><small>Plan reviewed {planReviewed} · daily calendar through 13 Jun 2027</small></div></header>
 <nav aria-label="Main navigation">{[['plan','Training'],['records','Records & Garmin'],['coach','Coaching'],['races','Race HQ'],['season','Season']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {message&&<p className="save-message" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss message">×</button></p>}
 {tab==='plan'&&<section><div className="section-head"><div><p className="eyebrow">01 / THE WORK</p><h2>Your daily prescription</h2><p>Primary training first. Open a day for exercises, pace, load, rest and an optional second session.</p></div><button onClick={()=>{setWeekId(current.id);setArchive(false)}}>Today’s week</button></div>
 <div className="controls"><label>Training week<select value={week.id} onChange={e=>setWeekId(e.target.value)}>{weeks.filter(w=>archive||dateOf(w.days[6])>=today||w.id===weekId).map(w=><option key={w.id} value={w.id}>{w.label} · {w.dates} · {w.phase}</option>)}</select></label><label className="inline"><input type="checkbox" checked={archive} onChange={e=>setArchive(e.target.checked)}/>Include historical weeks</label></div>
 <div className="week-heading"><div><span className="tag">{week.phase}</span><h3>{week.dates}</h3><p>{week.focus}</p></div><strong>{week.days.filter(d=>completed[d.id]).length}<small> / 7 marked</small></strong></div>
 <div className="callout"><b>The one gate</b><p>{week.gate||'Historical prescriptions and verified workout details are preserved. A checkbox is your own log; it does not prove a Garmin completion.'}</p></div>
 <div className="day-list">{week.days.map(d=><details className="day-card" key={d.id} open={dateOf(d)===today?true:undefined}><summary><span className="date">{d.dow}<b>{d.date}</b></span><span className="day-name"><b>{d.title}</b><small>{d.duration} · RPE {d.rpe}</small></span><span className="tag">{d.type}</span><span className="expand">+</span></summary><div className="day-content"><label className="inline completion"><input type="checkbox" checked={!!completed[d.id]} onChange={()=>toggle(d.id)}/>Primary completed</label>{d.blocks?.map((b,i)=><div className="workout-block" key={i}><h4>{b.label}</h4><ul>{b.items.map((item,j)=><li key={j}>{item}</li>)}</ul></div>)}{d.note&&<p className="coach-note">{d.note}</p>}{d.secondary&&<div className="secondary"><p className="eyebrow">SECOND SESSION / OPTIONAL</p><h4>{d.secondary.title}</h4><ul>{d.secondary.items.map(x=><li key={x}>{x}</li>)}</ul>{!d.secondary.title.startsWith('No second')&&<label className="inline"><input type="checkbox" checked={!!completed[d.id+'-secondary']} onChange={()=>toggle(d.id+'-secondary')}/>Optional session completed</label>}</div>}</div></details>)}</div>
 <p className="muted">Every key session has a target: pace, load or time. Log what you did; the Sunday review uses it to progress, hold or repeat the next week. Pace and load progressions live in Coaching.</p></section>}
 {tab==='records'&&<section><div className="section-head"><div><p className="eyebrow">02 / THE EVIDENCE</p><h2>Records & Garmin</h2><p>One record centre. Device metrics, self-reports and verified results keep their source labels.</p></div><button onClick={()=>download('race-hq-private-backup.json',{version:1,exportedAt:new Date().toISOString(),storage:Object.fromEntries(keys.map(k=>[k,read(k,null)]))})}>Export private backup</button></div>
 <div className="metric-grid"><article><small>LATEST REVIEW</small><b>20 SEP</b><p>20 September 2026. Connector window: 18–20 Sep; no live sync.</p></article><article><small>LATEST VERIFIED RUN</small><b>15.16 km</b><p>20 Sep · 1:30:01 · approximately 5:56/km.</p></article><article><small>WORKOUT AUTHORITY</small><b>Performance season</b><p>From 6 October one season plan drives every day. Historical sessions are unchanged.</p></article><article><small>PRIVATE DATA</small><b>{Object.keys(snapshot.healthByDate||{}).length} days</b><p>Imported health history on this device. Not sent to the public website.</p></article></div>
 <div className="callout"><b>Freshness is explicit</b><p>The connector review covers 18–20 September; older strength evidence comes from supplied screenshots. This is not a complete weekly Garmin dataset. The old August review is retained below as historical context. There is no live Garmin connection in this public page.</p><label className="file-button">Import private snapshot / backup<input type="file" accept="application/json,.json" onChange={e=>importData(e.target.files?.[0])}/></label><p>Private entries stay in this browser, are not encrypted and do not sync automatically. Export a backup before changing device or clearing browser data. Never use a shared device for sensitive notes.</p></div>
 <div className="subnav">{[['daily','Imported health'],['sessions','Training log'],['results','Verified results']].map(([id,label])=><button key={id} className={recordView===id?'active':''} onClick={()=>setRecordView(id)}>{label}</button>)}</div>
 {recordView==='daily'&&<> <h3>Imported Garmin health history</h3>{snapshot.lastSuccessfulSnapshotAt&&<p>Snapshot: {snapshot.lastSuccessfulSnapshotAt} · latest calendar day may be partial.</p>}{Object.keys(snapshot.healthByDate||{}).length>0?<Table heads={['Date','Sleep h','Sleep score','RHR','HRV ms','Stress','BB high / low']} rows={Object.entries(snapshot.healthByDate||{}).sort(([a],[b])=>b.localeCompare(a)).map(([date,h])=>[date,h.sleepHours??'—',h.sleepScore??'—',h.restingHeartRate??'—',h.hrvAverageMs??'—',h.stressAverage??'—',`${h.bodyBatteryHigh??'—'} / ${h.bodyBatteryLow??'—'}`])}/>:<p className="empty">Import your private compact snapshot to view sleep, HRV, stress and Body Battery here.</p>}{snapshot.supplementPurchases?.length ? <><h3>Private purchase inventory</h3><Table heads={['Product','Evidence date','Use status']} rows={snapshot.supplementPurchases.map(x=>[x.product,x.purchased,x.use])}/></> : null}</>}
 {recordView==='sessions'&&<><h3>Log actual work</h3><form onSubmit={session}><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Session<select name="slot"><option>Primary</option><option>Optional second</option><option>Unplanned</option></select></label><label>Duration, min<input name="minutes" type="number" min="1" max="600" required/></label><label>Session RPE 0–10<input name="rpe" type="number" min="0" max="10" required/></label><label className="wide">Exercise details / load / sets / pace / rest<textarea name="details" placeholder="Example: sled mass 42 kg + plates 110 kg = 152 kg total; 3 × 12.5 m; 24/25/25 sec; RPE 6" required/></label><button>Save session</button></form><p>Load = minutes × session RPE. It is a personal trend measure, not an injury prediction. Do not add Garmin and manual duration for the same session.</p>{logs.length>0&&<Table heads={['Date','Session','Minutes','RPE','Load','Details']} rows={[...logs].reverse().map(x=>[x.date,x.slot,x.minutes,x.rpe,x.load,x.details])}/>}
 <h3>Weekly sync · Strava and Runna calendar</h3>{(completions as Completion[]).length?<Table heads={['Date','Type','Planned','Recorded','Distance','Time','Pace','HR avg / max','Reps / stations','Note']} rows={[...(completions as Completion[])].reverse().map(c=>[c.date,c.type||'run',c.planned,c.title,c.distanceKm!==undefined?`${c.distanceKm} km`:'—',c.time||'—',c.pace||'—',c.avgHr?`${c.avgHr} / ${c.maxHr??'—'}`:'—',c.reps||c.stations||'—',c.note||'—'])}/>:<p className="empty">The Sunday sync adds your Garmin runs here each week.</p>}<h3>Strength log · from Strong screenshots</h3>{(strengthLog as StrengthEntry[]).length?<Table heads={['Date','Session','Top sets','Working sets','Note']} rows={[...(strengthLog as StrengthEntry[])].reverse().map(e=>[e.date,e.session,e.exercises.map(x=>`${x.name} ${topSet(x.sets)}`).join(' · '),e.exercises.reduce((n,x)=>n+x.sets.length,0),e.note||'—'])}/>:<p className="empty">Strength sessions appear here after you share your Strong screenshots.</p>}<h3>Verified training archive</h3><p>Detailed historical prescriptions and corrections remain accessible through the Training week selector. Completion checkboxes are preserved separately.</p><Table heads={['Date','Session','Evidence']} rows={actualRows.map(d=>[d.date,d.title,d.note||d.duration])}/><details><summary>Imported device activities ({snapshot.activities?.length||0})</summary><Table heads={['Date','Type','Distance km','Duration min']} rows={(snapshot.activities||[]).map(a=>[String(a.date||''),String(a.type||''),String(a.distanceKm??'—'),Math.round(Number(a.durationSeconds||0)/60)])}/></details></>}
 {recordView==='results'&&<><h3>Road results</h3><Table heads={['Date','Event','Distance','Net','Official','Pace','Context']} rows={roadResults.map(r=>[r.date,r.event,r.distance,r.net,r.official,r.pace,r.result])}/><h3>HYROX results</h3><Table heads={['Event','Division','Time','Context']} rows={raceHistory}/>{resultDetails.map((rows,i)=><details key={i}><summary>{['Kerry marathon checkpoints · chip cumulative','SCHK marathon checkpoints · official cumulative','Taipei Open Singles · complete station record'][i]}</summary><Table heads={rows[0]} rows={rows.slice(1)}/>{i===2&&<p>Station total 43:08; run 44:08; arithmetic leaves 10:06 for Roxzone/non-station time. The original HQ summary reports 10:10; the four-second discrepancy is retained.</p>}</details>)}<h3>Station priorities from historical singles</h3><Table heads={['Station','Earlier','Later Pro','Development need']} rows={singlesStationTrend}/><p>Different venues, loads and partners limit comparisons. Team times and device predictions are not individual race benchmarks.</p></>}
 <details className="archive"><summary>Historical Garmin aggregate · August 2026</summary><p>This dated review is preserved, not used as today’s readiness instruction.</p><p>{oldGarmin.summary}</p><Table heads={['Historical metric','Value','Context']} rows={oldGarmin.metrics.map(m=>[m.label,m.value,m.trend])}/></details></section>}
 {tab==='coach'&&<section><p className="eyebrow">03 / EXECUTION</p><h2>Specific enough to train well</h2><div className="callout"><b>Train to race, not to stay safe</b><p>The week is Monday lower strength, Tuesday easy run, Wednesday key run, Thursday upper strength + wall balls, Friday HYROX at race loads, Saturday rest, Sunday long run. Every key session has a number to hit. Hard days are hard; easy days stay easy.</p></div>
 <h3>20 September · performance review</h3><p>Data from Garmin (Forerunner 965), with strength details from supplied workout screenshots. Free-tier access covers 18–20 September; lap splits and multi-week recovery trends were unavailable.</p><Table heads={['Evidence','Observed change','Training decision']} rows={[
 ['20 Sep outdoor run · Forerunner 965','15.16 km in 1:30:01; approximately 5:56/km','Useful endurance exposure. Retain easy pace and threshold guide; one run does not prove race readiness.'],
 ['7 → 14 Sep squat · screenshots','40 kg × 4 → 50 kg × 4, best set','25% higher logged load, not 25% muscle growth. Progress working sets by reps before adding weight.'],
 ['7 → 14 Sep RDL / front squat · screenshots','30 kg × 6 → × 8; 20 kg × 7 → × 9','Rep progression is positive. Keep consistent range and equipment.'],
 ['11 → 18 Sep HYROX · screenshots','3 × 1 km both days; best km 5:15 → 5:25','Different station demand prevents a fitness decline conclusion. Do not invent a fourth repetition or total run time.'],
 ['11 → 18 Sep sleds · screenshots','Push 235 → 253 kg; pull 170 → 215 kg, best sets','Surface, empty-sled mass and distance units need consistency. Best sets are not race-equivalent loads.'],
 ['17 Sep upper strength · screenshot','28 main lifting sets plus trunk and additional machine work','Enough work to progress. Structured paired sets and a separated second exposure replace extra unplanned exercises.'],
 ]}/><p>Logged tonnage mixes unlike exercises and movement units; PR counts can reflect new exercises or logging history. Neither proves muscle gain. Track repeated sets on the same equipment and actual running performance. Insights derived in part from Garmin device-sourced data.</p><h3>How the plan changes</h3><Table heads={['Check','Rule']} rows={scheduleChangePolicy}/>
 <h3>Running pace guide · reviewed 5 October</h3><p>Set from your September 2026 threshold reps (4:54–5:07/km) and the Runna plan you used for the Kerry Marathon. Treadmill speeds are in kph; treadmill sessions use a 1% incline.</p><Table heads={['Purpose','Starting pace','Execution']} rows={paceGuide}/><h3>What carried over from Runna</h3><p>From the Runna plan for the Kerry Marathon (June–November 2025): the sessions suited you; the long-run volume and marathon pace did not.</p><Table heads={['','Element','In this plan']} rows={runnaLessons}/><p>Progression: when every rep of a key session lands on target at RPE 7 or less with even splits, the next one of that type is 5 sec/km faster. Check every two weeks. JPM, the Shanghai splits and a post-Osaka 5K time trial recalibrate the whole guide.</p>
 <h3>HYROX Pro Doubles Men · race standard</h3><Table heads={['Station','Team distance / repetitions','Race load']} rows={stations}/><p>Each athlete runs all 8 × 1 km; station work is shared. <a href="https://maintain.hyrox.com/rulebooks/HYROX_RulebookDoubles_EN.pdf" target="_blank" rel="noreferrer">Official 2026/27 doubles rulebook</a> · confirm final event briefing before racing.</p>
 <h3>Sleds · train at race load</h3><div className="callout"><b>Your logged best sets (253 kg push, 215 kg pull) are above race load.</b><p>So the plan uses race loads from now on: 202 kg total push and 153 kg total pull, in 12.5 m lengths. Record total = sled + plates, and keep the lane and shoes the same.</p></div><ol><li>Every sled length should be unbroken. If one stalls, finish the round at 10% less and return to race load next week.</li><li>Progress by shortening the rest between rounds or adding a round, never both in the same week.</li><li>Practise low hips, short fast steps, and on the pull a walk-back-and-pull rhythm. Time each length.</li></ol>
 <h3>Performance markers</h3><Table heads={['Marker','Now','Target','How the plan gets there']} rows={performanceMarkers}/><p>Progression uses repeatable sets and recovery, consistent with <a href="https://acsm.org/resistance-training-guidelines-update-2026/">ACSM resistance-training guidance</a>. Heavy compounds stay as straight sets; supersets organise accessories without cutting the rest needed for quality.</p><h3>Optional second-session rules</h3><p>Every future day has an explicit second-session decision. Separate workouts by at least six hours. Begin with one extra aerobic session/week; cap at two after two recovered weeks. Mobility is fine more often. Skip doubles after poor sleep, persistent soreness, illness or a harder-than-planned primary. Never shorten sleep to train twice.</p>
 <h3>Fuel, supplements & physique</h3><p>Prioritise regular meals and carbohydrate around demanding sessions. Aim for roughly 1.6–2.0 g protein/kg/day from food plus supplemental protein only as needed, spread across meals. Long runs are opportunities to practise 30–60 g carbohydrate/hour. Hydration needs vary; use thirst, conditions and measured sweat loss rather than forcing litres.</p><Table heads={['Product type','Role','Use decision']} rows={[
 ['Whey isolate','Convenient complete protein','20–30 g protein when a meal is impractical; count toward daily intake, not an extra requirement'],['Glutamine','No consistent performance or muscle-building benefit in adequately nourished athletes','Low priority; no automatic daily protocol'],['Collagen peptides','Potential adjunct; evidence remains limited','Does not replace complete protein or progressive rehabilitation'],['Magnesium glycinate','Correct inadequate intake when indicated','Check elemental magnesium on label and other products; more is not better'],['Multivitamin','Possible dietary gap coverage','Avoid stacked high-dose micronutrients; no promised endurance benefit'],['Creatine monohydrate','Evidence for strength / repeated high-intensity work','Optional future discussion, not inferred as purchased or required; body-mass and tolerance trade-offs']
 ]}/><p>Purchases do not establish what you currently take. Keep actual products, doses and tolerance in your private notes. Verify batch testing for competitive sport. Magnesium from supplements can cause diarrhoea and interact with some medicines; review the actual label and medicines before a dose recommendation. See <a href="https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/">NIH performance supplement guidance</a> and <a href="https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional/">NIH magnesium guidance</a>.</p><p>For visible abs, first establish consistent weight/waist measurements, food intake and training tolerance. Avoid aggressive dieting through race builds: low energy availability can harm male athletes’ health and performance. <a href="https://bjsm.bmj.com/content/57/17/1073">IOC REDs consensus</a>. No physique deadline or professional-athlete guarantee is credible from the current evidence.</p></section>}
 {tab==='races'&&<section><p className="eyebrow">04 / RACE HQ</p><h2>One race campaign · earliest first</h2><p>Tokyo: ballot unsuccessful. Pici Pasta Run 2026: excluded by choice. Neither creates a training target or registration alert.</p><h3>Upcoming timeline · all active statuses</h3><Table heads={['Date','Event','Status']} rows={races.filter(r=>r.startIso>=today&&r.status!=='DONE'&&!r.status.includes('CONFLICT')).map(r=>[r.date,r.name,r.status])}/><p>Fitz road-race scan: 20 September. 26 September and 11 October candidates overlap reduced availability; December 6 and 27 also conflict. October 25 RAC entry status is inconsistent, so no entry recommendation. <a href="https://fitz.hk/hksports-timetable/">Fitz calendar</a> · <a href="https://joymiles.hk/product/rac10k/">RAC organizer</a>. Monitoring continues; dates alone do not establish open registration.</p>{[['Confirmed & training toward',races.filter(r=>r.category==='campaign'&&r.status!=='DONE'&&!r.status.includes('CONFLICT')&&r.startIso>=today)],['Registration opportunities · date order',races.filter(r=>r.category!=='campaign'&&r.startIso>=today)],['Inactive / retained entry record',races.filter(r=>r.status.includes('CONFLICT'))]].map(([title,list])=><div key={String(title)}><h3>{String(title)}</h3><div className="race-grid">{(list as typeof races).map(r=><article key={r.name}><span className="tag">{r.status}</span><h4>{r.name}</h4><b>{r.date} · {r.type}</b><p>{r.note}</p>{r.sourceUrl&&<a href={r.sourceUrl} target="_blank" rel="noreferrer">{r.sourceLabel}</a>}<small>Reviewed {r.checked}</small></article>)}</div></div>)}<details><summary>Optional Procam sequence</summary>{procamEvents.map(r=><article key={r.name}><h4>{r.name} · {r.date}</h4><p>{r.registration} · {r.fit}</p><a href={r.sourceUrl}>Official information</a></article>)}</details><p>Completed events are in Records. A target is a committed planning goal, not proof of personal registration. Ballots remain unconfirmed until selected and paid.</p></section>}
 {tab==='season'&&<section><p className="eyebrow">05 / THE LONG VIEW</p><h2>Ranked goals. One season.</h2><p>Born April 1990: you race Hong Kong and Bangkok at 36. When two goals compete, the higher one wins.</p><Table heads={['Rank','Race','Target']} rows={seasonGoals}/><h3>Season shape</h3><Table heads={['Window','Focus','Detail']} rows={season}/><h3>Next six weeks</h3><Table heads={['Week','Phase','Volume','Focus']} rows={upcoming.map(w=>[`${w.label} · ${w.dates}`,w.phase,w.volume,w.focus])}/><h3>Weekly review · Sunday</h3><ol><li>Compare each key session’s target with what you did: splits, loads, station and transition times.</li><li>Make one decision for next week: progress (all targets hit at RPE 7 or less), hold, or repeat.</li><li>Sleep, HRV and Body Battery are context for that decision, not a reason to change a single day.</li><li>Recheck race entries and partner plans before each taper.</li></ol></section>}
 <footer>AMAR / ENDURANCE LAB <span>One plan · one record · consistent progression</span></footer>
 </main>;
}
