import type { Day } from './trainingHistory';
const block=(label:string,items:string[])=>({label,items});
const prep=block('WARM-UP · 8–10 MIN',['Easy bike or jog, then ankle rocks, bodyweight squats and hinges: 8 each.','Before the first compound lift: 2–3 progressively heavier warm-up sets. Warm-ups do not count as work sets.']);
export function reviseFuture(day:Day,deload:boolean):Day {
 if(!day.iso || day.iso<'2026-09-21')return day;
 const d={...day};
 if(d.travel && !d.race && d.type!=='RECOVERY'){
  d.title='Optional hotel gym · or full rest';d.type='OPTIONAL';d.duration='0–35 min';d.rpe='0 or 4–6';
  d.blocks=[block('CHOOSE ONE · SKIPPING IS VALID',['Hotel gym assumed: basic dumbbells, bench and cardio machine. Use bodyweight if an item is unavailable.','Choose the strength option OR 20–30 min easy treadmill/bike at conversational effort. Full rest is equally valid; no catch-up sessions.']),block('OPTION A · FULL-BODY · 2 ROUNDS',['Warm up 5 min on bike or treadmill.','A1 · Goblet squat: 8–10 reps.','A2 · Dumbbell row: 10–12 reps/side. Rest 75–90 sec after the pair.','B1 · Dumbbell Romanian deadlift: 8–10 reps.','B2 · Dumbbell bench press or push-ups: 8–12 reps. Rest 75–90 sec after the pair.','C · Calf raise: 12–15 reps; side plank: 20–30 sec/side.','Keep 3–4 reps in reserve. No failure, new exercises or hard intervals. Leave at least 48 hours between hotel strength sessions.']),block('OPTION B · EASY AEROBIC',['20–30 min treadmill walk/jog or bike, RPE 3. Use effort rather than chasing outdoor pace.','Travel, poor sleep or a walking-heavy day: choose rest.'])];
  d.note='Optional maintenance during reduced availability. This session does not create a requirement to train.';
 }else if(d.title==='Lower-body strength & tendon capacity'){
  d.title='Lower strength · squat, hinge & single-leg';d.duration=deload?'45–55 min':'65–75 min';d.rpe=deload?'5–6':'7–8';
  d.blocks=[prep,block('A · STRAIGHT SETS · NO SUPERSET',[`Back squat: ${deload?2:4} × 4–6. Rest 2½–3 min; keep 2 reps in reserve.`,`50 kg × 4 is a logged best set, not proof that every set should use 50 kg. Start at 45–50 kg only if warm-ups and clean reps support it; otherwise reduce.`,`Romanian deadlift: ${deload?2:3} × 6–8. Start around the logged 30 kg; keep 2 reps in reserve, rest 2 min.`]),block('B · ACCESSORY SUPERSET',[`B1 · Rear-foot-supported split squat: ${deload?2:3} × 8/side. Choose a stable load; confirm whether logged dumbbell weight is per hand.`,`B2 · Hamstring curl: ${deload?2:3} × 10–12.`,`Alternate B1 then B2; rest 90 sec after the pair. Leave 2 reps in reserve.`]),block('C · CALF & SHIN · CONTROLLED SETS',[`Bent-knee calf raise: ${deload?2:3} × 12–15.`,`Standing calf raise: ${deload?2:3} × 12–15.`,`Tibialis raise: 2 × 15–25. Rest 60 sec between sets; use a comfortable range.`]),block('PROGRESSION',['Add reps within the range first. Once all sets reach the top with 2 reps left on two exposures, add the smallest load increment, usually 2.5–5%.','No extra front-squat sets: the squat and split squat already cover knee-dominant work. Keep the last set technically as clean as the first.','After a Sunday long run, retain Monday legs if warm-up is normal; if not, reduce sets or use the existing alternative. Never force a heavy day through altered gait.'])];
 }else if(d.title==='Upper-body strength & trunk'){
  d.title='Upper strength & muscle · paired sets';d.duration=deload?'40–50 min':'60–75 min';d.rpe=deload?'5–6':'7–8';
  d.blocks=[prep,block('A · PUSH / PULL PAIRED SETS',[`A1 · Chest press: ${deload?2:4} × 6–10.`,`A2 · Chest-supported row: ${deload?2:4} × 8–10.`,`Rest 90 sec between A1 and A2, and 90 sec before repeating. Keep 2 reps in reserve. Machine loads must match the same equipment.`]),block('B · VERTICAL PUSH / PULL',[`B1 · Lat pulldown: ${deload?2:3} × 8–12.`,`B2 · Seated shoulder press: ${deload?2:3} × 8–10.`,`Rest 75–90 sec between exercises. Keep 2 reps in reserve.`]),block('C · SHOULDER SUPERSET',[`C1 · Lateral raise: ${deload?2:3} × 12–15.`,`C2 · Reverse fly: ${deload?2:3} × 12–15. Rest 60–75 sec after the pair.`]),block('D · ARM SUPERSET',[`D1 · Cable curl: ${deload?2:3} × 10–15.`,`D2 · Triceps pushdown: ${deload?2:3} × 10–15. Rest 60–75 sec after the pair.`]),block('E · TRUNK',['Pallof press: 2 × 10/side.','Side plank: 2 × 30 sec/side. Rest 45 sec.','When all sets reach the top of the range twice with clean technique, add the smallest available load. Avoid adding extra machines after this session.'])];
 }
 if(d.type==='HYROX'){
  d.blocks=d.blocks?.map(b=>({...b,items:b.items.flatMap(x=>x.startsWith('SkiErg 250')?['SkiErg: 250 m at RPE 6, 24–30 strokes/min.','Row: 250 m at RPE 6, 22–26 strokes/min.','Record pace/500 m; hold within 5 sec across rounds.']:x.startsWith('Sandbag lunges')?['Sandbag lunge: 20 m with 20–30 kg total. Use the logged 30 kg only with legal, repeatable steps.','Burpee broad jump: 10 m, smooth legal repetitions; no maximal jumps.']:x.startsWith('Farmers carry')?['Farmers carry: 50 m with 2 × 32 kg if repeatable and unbroken; otherwise 2 × 24 kg.','Wall balls: 15 legal reps at 9 kg. Reduce to 6 kg if depth or target fails.']:x.startsWith('Push 12.5')?['Sled push: 12.5 m, calibrated RPE 6–7 working load.','Sled pull: 12.5 m, calibrated RPE 6–7 working load.','Keep the same sled and surface. Logged 253/215 kg best sets do not establish repeatable working loads or race-equivalent resistance. Use the Coaching calibration protocol; avoid stalls.']:[x])}));
 }
 if(!d.travel && !deload && d.type==='EASY' && d.dow==='TUE' && d.secondary?.title==='Optional · upper-body support · 25–30 min' && !(d.iso!>='2026-12-15'&&d.iso!<='2026-12-20')) d.secondary={title:'Optional · second upper exposure · 30–40 min',items:['Separate from the run by at least 6 hours; keep 48 hours before Thursday upper strength. Skip in taper, recovery or travel weeks.','A1 · Dumbbell incline press: 3 × 8–12.','A2 · Supported row: 3 × 10–12. Rest 90 sec after each pair.','B1 · Lateral raise: 2 × 12–15.','B2 · Cable curl: 2 × 10–15. Rest 60 sec after each pair.','Leave 2–3 reps in reserve. This is the only extra muscle session this week; do not also add the generic upper support session.']};
 if(deload && !d.travel)d.secondary={title:'No second workout today',items:['Deload: retain primary technique and absorb the previous work. Optional gentle mobility only.']};
 return d;
}
export const buildOutlook=[
 ['21–27 Sep','Strength progression + travel maintenance','Mon lower; Tue 8 km easy + optional upper; Wed 3 × 8 min threshold; Thu upper; Fri–Sun optional hotel gym or rest.'],
 ['28 Sep–4 Oct','Build, then assess','Mon lower; Tue 8 km easy + optional upper; Wed 6 × 2 min; Thu upper; Fri 3 × 1 km HYROX; Sun 16 km easy. Advance only if the last 15.16 km was well tolerated.'],
 ['5–11 Oct','Deload + reduced availability','Reduce strength sets; 6 km easy; 2 × 6 min threshold. Optional hotel sessions from 9 Oct. No catch-up long run.'],
 ['12–18 Oct','Rebuild after travel','12 Oct optional hotel session/rest; resume planned easy/quality/upper/HYROX. Sunday 14 km easy.'],
 ['19–25 Oct','Final full build','Normal strength; one quality run; one HYROX session; Sunday controlled 10 km. Pici is excluded.'],
 ['26 Oct–1 Nov','Rehearsal week','Reduce strength volume, short running touches, then registered Shanghai Pro Doubles on 1 Nov.'],
];
