export type Race = {
  startIso: string;
  date: string;
  name: string;
  type: string;
  status: string;
  priority: string;
  location: string;
  note: string;
  category: "campaign" | "opportunity" | "hyrox";
  sourceLabel: string;
  sourceUrl?: string;
  checked: string;
};

export type ProcamEvent = {
  order: string;
  date: string;
  name: string;
  feature: string;
  registration: string;
  fit: string;
  sourceUrl: string;
};

export const races: Race[] = [
  { startIso: "2026-07-25", date: "25 Jul 2026", name: "HYROX Delhi", type: "Pro Doubles Men", status: "DONE", priority: "Context", location: "Delhi", note: "1:27:54 · AG 14 · Overall 91. Partner-paced running and a larger station share make this a team result, not Amar's individual fitness baseline.", category: "campaign", sourceLabel: "RESULT", checked: "25 Jul 2026" },
  { startIso: "2026-08-30", date: "30 Aug 2026", name: "PEGASUS Tsuen Wan 10K", type: "Road 10K", status: "REGISTERED", priority: "A RUN", location: "Hong Kong", note: "Primary calibration race. Garmin currently predicts about 46:46; race by effort and use the result to reset September threshold pace. The stated 15-minute target is held for clarification because it is not a plausible 10K finish time.", category: "campaign", sourceLabel: "USER CONFIRMED", checked: "9 Aug 2026" },
  { startIso: "2026-11-05", date: "5 Nov 2026 · 6:30 p.m.", name: "JPMorganChase Corporate Challenge", type: "5.6K road", status: "TARGET", priority: "A RUN", location: "West Kowloon, Hong Kong", note: "Official date confirmed. Improve on 25:27; 22:00 is a stretch goal requiring about 3:56/km and a large gain from Garmin's current 22:01 5K prediction. Prioritize this over an all-out Shanghai race four to five days earlier.", category: "campaign", sourceLabel: "OFFICIAL EVENT", sourceUrl: "https://www.jpmorganchasecc.com/en/home/our-locations/hong-kong/the-event", checked: "9 Aug 2026" },
  { startIso: "2027-01-17", date: "17 Jan 2027", name: "Standard Chartered Hong Kong Marathon", type: "Marathon / Half / 10K option", status: "DO NOT ENTER YET", priority: "Skip marathon", location: "Hong Kong", note: "One week after HYROX Hong Kong. Do not enter the marathon. A shorter distance can be reconsidered only if the January HYROX entry is missed and recovery is green.", category: "opportunity", sourceLabel: "OFFICIAL ORGANISER", sourceUrl: "https://www.hkmarathon.com/", checked: "15 Aug 2026" },

  { startIso: "2026-09-12", date: "12 Sep 2026 · 8:00 a.m.", name: "AVOHK 5K Series · Race 4", type: "Road 5K", status: "OPTIONAL · ENTRY LINK LIVE", priority: "B", location: "South Bay, Hong Kong", note: "The September speed option worth retaining. It falls two weeks after PEGASUS, making it a useful controlled 5K benchmark if recovery is green. Prefer this to the hillier Black’s Link race on 5 September; do not turn both into hard races.", category: "opportunity", sourceLabel: "OFFICIAL ORGANISER", sourceUrl: "https://avohk.org/index.php/2026/08/09/2026-avohk-5k-series-entry-is-now-open-sign-up-now/", checked: "18 Aug 2026" },\n  { startIso: "2026-11-08", date: "8 Nov 2026", name: "RMAC Gold Coast 15K", type: "Road 15K", status: "OPTIONAL · OPEN", priority: "B", location: "Hong Kong", note: "The only November road option worth retaining. Enter only if Guangzhou remains the primary HYROX race and run this as controlled aerobic work, not a second peak after JPMCC.", category: "opportunity", sourceLabel: "OFFICIAL ENTRY", sourceUrl: "https://www.jotform.com/262032160097449", checked: "15 Aug 2026" },
  { startIso: "2026-11-15", date: "15 Nov 2026", name: "Pocari Sweat Run Fest 10K", type: "Road 10K", status: "DO NOT ENTER", priority: "Skip", location: "Hong Kong", note: "Six days before HYROX Guangzhou. Even a controlled 10K adds avoidable fatigue and logistical load during race week.", category: "opportunity", sourceLabel: "OFFICIAL ENTRY", sourceUrl: "https://psrun2026.sportsoho.com/en/form/enrolment-form", checked: "15 Aug 2026" },
  { startIso: "2026-12-06", date: "6 Dec 2026 · 4:30 a.m.", name: "BYD Singapore International Marathon", type: "Full road marathon", status: "OPEN · CLOSES 30 SEP", priority: "Strategy fork", location: "Singapore", note: "The best credible Q4 marathon still open, with a Gold Label road race and simple direct travel from Hong Kong. It is not in the recommended campaign: it falls 14 days after HYROX Guangzhou and 32 days before HYROX Hong Kong. Enter only if Guangzhou is deliberately dropped, ASICS Half is removed, and the next eight weeks become a marathon-specific build.", category: "opportunity", sourceLabel: "OFFICIAL ORGANISER", sourceUrl: "https://singaporeinternationalmarathon.com/", checked: "15 Aug 2026" },
  { startIso: "2026-12-13", date: "13 Dec 2026 · 7:45 a.m.", name: "ASICS Hong Kong Half-Marathon Championships", type: "Road half marathon", status: "REGISTER 27 AUG", priority: "B+", location: "Tai Mei Tuk, Hong Kong", note: "Recommended controlled benchmark three weeks after Guangzhou and four weeks before HYROX Hong Kong. Prior completion on 21 Dec 2025 makes the timing familiar; exact prior finish time will be pulled from the private Garmin archive by date and distance, not activity title.", category: "opportunity", sourceLabel: "OFFICIAL HKAAA", sourceUrl: "https://hkaaa.com/en/comp_details.php?id=293", checked: "15 Aug 2026" },

  { startIso: "2026-10-31", date: "31 Oct–1 Nov 2026", name: "HYROX Shanghai", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "Reserve", location: "Shanghai", note: "Official page still gives no sale date. Do not A-race this and JPMCC four days later. Buy only if the team commits and JPMCC becomes a controlled effort.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-shanghai-1031/", checked: "15 Aug 2026" },
  { startIso: "2026-11-21", date: "21–22 Nov 2026", name: "HYROX Guangzhou", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "PRIMARY", location: "Guangzhou", note: "First-choice qualification attempt. Official page still gives no sale date. Register immediately when Pro Doubles Men opens, provided the partner is confirmed.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-guangzhou/", checked: "15 Aug 2026" },
  { startIso: "2026-11-27", date: "27–28 Nov 2026", name: "HYROX Gujarat · Gandhinagar", type: "Pro Doubles Men watch", status: "DO NOT ENTER", priority: "Skip", location: "Gandhinagar", note: "Only five to seven days after Guangzhou and travel-heavy from Hong Kong. It is not a viable second peak.", category: "hyrox", sourceLabel: "OFFICIAL HYROX INDIA", sourceUrl: "https://hyrox.co.in/event/hyrox-gujarat/", checked: "15 Aug 2026" },
  { startIso: "2027-01-07", date: "7–10 Jan 2027", name: "AIA HYROX Hong Kong", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "PRIMARY", location: "Hong Kong", note: "Home qualification attempt and automatic priority over every January marathon. Official page still gives no sale date; register immediately when Pro Doubles Men opens.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-hong-kong/", checked: "15 Aug 2026" },
  { startIso: "2027-01-15", date: "15–17 Jan 2027", name: "HYROX Greater Noida", type: "Pro Doubles Men watch", status: "DO NOT ENTER", priority: "Skip", location: "Greater Noida", note: "Only five to ten days after HYROX Hong Kong and travel-heavy. Not compatible with a proper recovery and build cycle.", category: "hyrox", sourceLabel: "OFFICIAL HYROX INDIA", sourceUrl: "https://hyrox.co.in/event/hyrox-noida/", checked: "15 Aug 2026" },
  { startIso: "2027-01-21", date: "21–24 Jan 2027", name: "BYD HYROX Osaka", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "Reserve", location: "Osaka", note: "Official page has no sale date. Use only if Hong Kong is missed, not as a second race 11–17 days later.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/byd-hyrox-osaka/", checked: "15 Aug 2026" },
  { startIso: "2027-02-11", date: "11–14 Feb 2027", name: "BYD HYROX Bangkok", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "BACKUP 1", location: "Bangkok", note: "Best backup qualification window if Guangzhou and Hong Kong do not secure the goal. Do not activate it while a January race remains the current target.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-bangkok/", checked: "15 Aug 2026" },
  { startIso: "2027-03-12", date: "12–14 Mar 2027", name: "HYROX Taipei", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "BACKUP 2", location: "Taipei", note: "Second backup only. Official page gives no sale date. Short-haul travel and a clean four-week build make it preferable to stacking January races.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-taipei/", checked: "15 Aug 2026" },
  { startIso: "2027-04-16", date: "16–18 Apr 2027", name: "HYROX Nagoya", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "Contingency", location: "Nagoya", note: "Late contingency if qualification remains open. Official page gives no sale date. Keep out of the active training plan until the March outcome is known.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-nagoya/", checked: "15 Aug 2026" },
  { startIso: "2027-05-12", date: "12–16 May 2027", name: "HYROX Bengaluru", type: "Pro Doubles Men watch", status: "EMERGENCY ONLY", priority: "Risk", location: "Bengaluru", note: "Last qualifying weekend. Use only if all earlier attempts fail; the turnaround to Worlds is too short for this to be the plan.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-bengaluru/", checked: "15 Aug 2026" },
  { startIso: "2027-05-13", date: "13–16 May 2027", name: "BYD HYROX Incheon", type: "Pro Doubles Men watch", status: "EMERGENCY ONLY", priority: "Risk", location: "Incheon", note: "Same last qualifying weekend as Bengaluru. Choose neither by default and never enter both.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-incheon/", checked: "15 Aug 2026" },
  { startIso: "2027-06-10", date: "10–13 Jun 2027", name: "PUMA HYROX World Championships", type: "Pro Doubles Men", status: "QUALIFICATION REQUIRED", priority: "A+", location: "Hong Kong", note: "Target, not an open-entry race. A Pro or Mixed Doubles age-group slot must be earned and then accepted within HYROX's 48-hour invitation window.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/puma-hyrox-world-championships-hong-kong/", checked: "15 Aug 2026" },
];

export const procamEvents: ProcamEvent[] = [
  { order: "START", date: "20 Dec 2026", name: "Tata Steel World 25K Kolkata", feature: "25K · Slam cutoff 3:45", registration: "OPEN · UNTIL CAPACITY (NO CLOSING DATE PUBLISHED)", fit: "Optional cycle start, but it comes four weeks after HYROX Guangzhou and adds another overseas peak. Enter only if recovered and the 25K serves a clear run goal; do not let it displace HYROX recovery.", sourceUrl: "https://tatasteelworld25k.procam.in/race-categories/25k-run/registration-dates" },
  { order: "2", date: "17 Jan 2027", name: "Tata Mumbai Marathon", feature: "Marathon · Slam cutoff 6:30", registration: "OPEN · CLOSES 5 NOV OR WHEN FULL", fit: "Overseas marathon entry is open. Same date as Hong Kong Marathon and one week after HYROX Hong Kong.", sourceUrl: "https://tatamumbaimarathon.procam.in/race-categories/marathon/registration-date" },
  { order: "3", date: "25 Apr 2027", name: "TCS World 10K Bengaluru", feature: "Open 10K · Slam cutoff 1:25", registration: "RACE DATE CONFIRMED · REGISTRATION TBC", fit: "Good distance for the running plan, but travel cost must justify it during the final HYROX qualifier block.", sourceUrl: "https://tcsworld10k.procam.in/" },
  { order: "4", date: "2027 date TBC", name: "Vedanta Delhi Half Marathon", feature: "Half Marathon · Slam cutoff 3:30", registration: "2027 WINDOW TBC", fit: "The sold-out 18 Oct 2026 edition is intentionally excluded from active opportunities.", sourceUrl: "https://vedantadelhihalfmarathon.procam.in/" },
];
