export type Race = {
  startIso: string;
  date: string;
  name: string;
  type: string;
  status: string;
  priority: string;
  location: string;
  note: string;
  category: "campaign" | "opportunity" | "hyrox";
  sourceLabel: string;
  sourceUrl?: string;
  checked: string;
};

export type ProcamEvent = {
  order: string;
  date: string;
  name: string;
  feature: string;
  registration: string;
  fit: string;
  sourceUrl: string;
};

export const races: Race[] = [
  { startIso: "2026-07-25", date: "25 Jul 2026", name: "HYROX Delhi", type: "Pro Doubles Men", status: "DONE", priority: "Context", location: "Delhi", note: "1:27:54 · AG 14 · Overall 91. Partner-paced running and a larger station share make this a team result, not Amar's individual fitness baseline.", category: "campaign", sourceLabel: "RESULT", checked: "25 Jul 2026" },
  { startIso: "2026-08-30", date: "30 Aug 2026 · 8:20 a.m.", name: "PEGASUS Tsuen Wan 10K", type: "Road 10K", status: "DONE", priority: "CALIBRATION", location: "Hong Kong", note: "Garmin result: 1:03:25 over 10.17 km (about 6:14/km). Retain as a completed race, not a threshold benchmark.", category: "campaign", sourceLabel: "GARMIN RESULT", checked: "30 Aug 2026" },
  { startIso: "2026-11-05", date: "5 Nov 2026 · 6:30 p.m.", name: "JPMorganChase Corporate Challenge", type: "5.6K road", status: "TARGET", priority: "A RUN", location: "West Kowloon, Hong Kong", note: "Official date confirmed. Improve on 25:27; 22:00 is a stretch goal requiring about 3:56/km; retain it as a goal, not an established race pace. Prioritize this over an all-out Shanghai race four days earlier.", category: "campaign", sourceLabel: "OFFICIAL EVENT", sourceUrl: "https://www.jpmorganchasecc.com/en/home/our-locations/hong-kong/the-event", checked: "9 Aug 2026" },
  { startIso: "2026-11-08", date: "8 Nov 2026", name: "RMAC Gold Coast 15K", type: "Road 15K", status: "REGISTERED", priority: "B RUN", location: "Hong Kong", note: "Personal registration is confirmed. Run it as a controlled aerobic 15K three days after JPMorganChase, not as a second all-out peak; reduce or skip if the 5.6K leaves residual soreness.", category: "campaign", sourceLabel: "PERSONAL REGISTRATION", sourceUrl: "https://www.jotform.com/262032160097449", checked: "21 Aug 2026" },
  { startIso: "2027-01-09", date: "9 Jan 2027 · afternoon", name: "AIA HYROX Hong Kong · Pro Doubles Men", type: "Pro Doubles Men", status: "REGISTERED", priority: "A+ HYROX", location: "Hong Kong", note: "Paid entry is confirmed for the Saturday afternoon Pro Doubles Men race. This is now the primary home qualification attempt and the January training peak. The 15 September live checkout shows both the standard and charity Pro Doubles Men tickets sold out. Continue privately watching for another official re-release; no additional purchase is needed for Amar. No additional purchase is needed for Amar. Required action: personalise both athlete tickets and download the QR codes; do not publish ticket or order details.", category: "campaign", sourceLabel: "PERSONAL REGISTRATION", sourceUrl: "https://hyrox.com/event/hyrox-hong-kong/", checked: "15 Sep 2026" },
  { startIso: "2026-12-13", date: "13 Dec 2026 · 7:45 a.m.", name: "ASICS Hong Kong Half-Marathon Championships", type: "Road half marathon", status: "REGISTERED · AVAILABILITY CONFLICT", priority: "INACTIVE", location: "Tai Mei Tuk, Hong Kong", note: "Entry remains paid and registered, but the race is incompatible with current availability. Removed from the active training campaign; do not build or taper for this event. Reconsider only if availability explicitly changes. The prior 2025 result is retained in Records.", category: "campaign", sourceLabel: "PERSONAL REGISTRATION", sourceUrl: "https://hkaaa.com/en/comp_details.php?id=293", checked: "13 Sep 2026" },
  { startIso: "2027-01-17", date: "17 Jan 2027 · start time allocated later", name: "Standard Chartered Hong Kong Marathon 2027 · Half Marathon", type: "Road half marathon", status: "BALLOT SUBMITTED · RESULT 25 SEP", priority: "B RUN", location: "Hong Kong", note: "Personal public-ballot application is submitted for the Half Marathon, not the full marathon. This is not confirmed until selection and payment. First-round results open 25 September at 2:00 p.m. HKT; if selected, payment is due by 2 October at 11:59 p.m. HKT. A second round may open 7 October with payment due 10 October. The race is eight days after HYROX Hong Kong, so keep it recovery-dependent and controlled rather than treating it as another peak. It conflicts directly with Tata Mumbai Marathon on the same day; never plan both.", category: "opportunity", sourceLabel: "PERSONAL APPLICATION", sourceUrl: "https://www.hkmarathon.com/important-dates", checked: "11 Sep 2026" },

  { startIso: "2027-02-28", date: "28 Feb 2027 · 9:15 a.m.", name: "Osaka Marathon 2027", type: "Road marathon", status: "BALLOT SUBMITTED · RESULT 28 SEP", priority: "A BACKUP", location: "Osaka, Japan", note: "Personal overseas general-ballot application is submitted. This is not confirmed until selection and payment. Result is due 28 September. Tokyo ballot was unsuccessful. Osaka is the sole remaining Japan option, conditional on selection and payment.", category: "opportunity", sourceLabel: "OFFICIAL OSAKA", sourceUrl: "https://www.osaka-marathon.com/2027/en/runner/entry/admission/", checked: "21 Aug 2026" },

  { startIso: "2026-11-01", date: "1 Nov 2026 · Sunday", name: "ZhongAn HYROX Shanghai", type: "Pro Doubles Men", status: "REGISTERED", priority: "B+ HYROX", location: "Shanghai", note: "Paid entry and both athlete tickets are confirmed for Sunday. Use Shanghai as a controlled Pro Doubles rehearsal rather than a separate peak: no full taper, protect the 5 November JPMorganChase speed target, keep the preceding Sunday as an easy training run. Required action: personalise both athlete tickets and download the QR codes.", category: "campaign", sourceLabel: "PERSONAL REGISTRATION", sourceUrl: "https://hyrox.com/event/hyrox-shanghai-1031/", checked: "3 Sep 2026" },
  { startIso: "2026-11-21", date: "21–22 Nov 2026", name: "HYROX Guangzhou", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "OPTIONAL", location: "Guangzhou", note: "Optional additional race only. Hong Kong is the paid primary peak. No Guangzhou taper or race is activated until category availability, entry payment, partner and recovery are confirmed.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-guangzhou/", checked: "15 Aug 2026" },
  { startIso: "2027-02-11", date: "11–14 Feb 2027", name: "BYD HYROX Bangkok", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "BACKUP 1", location: "Bangkok", note: "Best backup qualification window if Guangzhou and Hong Kong do not secure the goal. Do not activate it while a January race remains the current target.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-bangkok/", checked: "15 Aug 2026" },
  { startIso: "2027-03-12", date: "12–14 Mar 2027", name: "HYROX Taipei", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "BACKUP 2", location: "Taipei", note: "Second backup only. Official page gives no sale date. Do not activate after a Japan marathon: this is only twelve to fourteen days after Osaka.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-taipei/", checked: "15 Aug 2026" },
  { startIso: "2027-04-16", date: "16–18 Apr 2027", name: "HYROX Nagoya", type: "Pro Doubles Men watch", status: "SALES SOON", priority: "Contingency", location: "Nagoya", note: "Late contingency if qualification remains open. Official page gives no sale date. Keep out of the active training plan until the March outcome is known.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-nagoya/", checked: "15 Aug 2026" },
  { startIso: "2027-05-12", date: "12–16 May 2027", name: "HYROX Bengaluru", type: "Pro Doubles Men watch", status: "EMERGENCY ONLY", priority: "Risk", location: "Bengaluru", note: "Last qualifying weekend. Use only if all earlier attempts fail; the turnaround to Worlds is too short for this to be the plan.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-bengaluru/", checked: "15 Aug 2026" },
  { startIso: "2027-05-13", date: "13–16 May 2027", name: "BYD HYROX Incheon", type: "Pro Doubles Men watch", status: "EMERGENCY ONLY", priority: "Risk", location: "Incheon", note: "Same last qualifying weekend as Bengaluru. Choose neither by default and never enter both.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/hyrox-incheon/", checked: "15 Aug 2026" },
  { startIso: "2027-06-10", date: "10–13 Jun 2027", name: "PUMA HYROX World Championships", type: "Pro Doubles Men", status: "QUALIFICATION REQUIRED", priority: "A+", location: "Hong Kong", note: "Target, not an open-entry race. A Pro or Mixed Doubles age-group slot must be earned and then accepted within HYROX's 48-hour invitation window.", category: "hyrox", sourceLabel: "OFFICIAL HYROX", sourceUrl: "https://hyrox.com/event/puma-hyrox-world-championships-hong-kong/", checked: "15 Aug 2026" },
];

export const procamEvents: ProcamEvent[] = [
  { order: "START", date: "20 Dec 2026", name: "Tata Steel World 25K Kolkata", feature: "25K · Slam cutoff 3:45", registration: "OPEN · 13 AUG 2026 09:30 HKT TO 28 NOV 2026 02:29 HKT, OR UNTIL FULL · CHECKED 13 SEP", fit: "Optional only; no change to the Hong Kong HYROX peak. Decide whether the extra 25K serves a clear endurance goal before applying. Standard entry requires an accepted chip-timed road certificate from 1 December 2024 onward: marathon ≤7:00, 25K ≤4:11, half ≤3:30 or 10K ≤1:22. Confirm course and timing eligibility with Procam; a Garmin activity alone is not a qualifying certificate.", sourceUrl: "https://tatasteelworld25k.procam.in/race-categories/25k-run/registration-dates" },
  { order: "2", date: "17 Jan 2027", name: "Tata Mumbai Marathon", feature: "Marathon · Slam cutoff 6:30", registration: "OPEN · 31 JUL 2026 09:30 HKT TO 6 NOV 2026 02:29 HKT, OR UNTIL FULL · CHECKED 13 SEP", fit: "Overseas marathon entry is open, but it is eight days after HYROX Hong Kong and directly conflicts with Amar's submitted Standard Chartered Hong Kong Half Marathon ballot. Do not enter while that ballot is active, and never plan both races.", sourceUrl: "https://tatamumbaimarathon.procam.in/race-categories/marathon/registration-date" },
  { order: "3", date: "25 Apr 2027", name: "TCS World 10K Bengaluru", feature: "Open 10K · Slam cutoff 1:25", registration: "RACE DATE CONFIRMED · REGISTRATION TBC", fit: "Good distance for the running plan, but travel cost must justify it during the final HYROX qualifier block.", sourceUrl: "https://tcsworld10k.procam.in/" },
  { order: "4", date: "2027 date TBC", name: "Vedanta Delhi Half Marathon", feature: "Half Marathon · Slam cutoff 3:30", registration: "2027 WINDOW TBC", fit: "The sold-out 18 Oct 2026 edition is intentionally excluded from active opportunities.", sourceUrl: "https://vedantadelhihalfmarathon.procam.in/" },
];

export const chronologicalRaces = [...races].sort((a,b)=>a.startIso.localeCompare(b.startIso)||a.name.localeCompare(b.name));
